name: Publish Agent Snapshot
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'

jobs:
  publish-snapshot-image:
    name: Publish Agent Snapshot to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Cache Golang Dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Operator Agent Image
        run: make docker-build

      - name: Login To Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Operator Agent Image
        run: make docker-push

  slack_notify:
    name: Slack Notify
    needs: [ 'publish-snapshot-image' ]
    if: always() &&  needs.publish-snapshot-image.result != 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@f3635935f58910a6d6951b73efe9037c960c8c04
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}